# Generated by Django 4.1.5 on 2023-04-09 08:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gyms.validations
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gyms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, validators=[gyms.validations.get_words])),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('fm', 'Female & Male')], max_length=2)),
                ('field_sport_gym', models.IntegerField(choices=[(1, 'Football'), (2, 'Volleyball'), (3, 'Swim'), (4, 'Basketball'), (5, 'Tennis'), (6, 'Table Tennis'), (7, 'Baseball'), (8, 'Golf'), (9, 'Wrestling'), (10, 'Bodybuilding'), (11, 'Boxing'), (12, 'Kung Fu'), (13, 'Karate'), (14, 'MMA'), (15, 'shooting'), (16, 'Jujitsu'), (17, 'taekwondo'), (18, 'water polo'), (19, 'Running'), (20, 'Mountaineering'), (21, 'Field hockey'), (22, 'bowling'), (23, 'handball'), (24, 'American football'), (25, 'futsal')])),
                ('days_work', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Saturday'), ('2', 'Sunday'), ('3', 'Monday'), ('4', 'Tuesday'), ('5', 'Wednesday'), ('6', 'Thursday'), ('7', 'Friday')], max_length=100)),
                ('time_start_working', models.TimeField()),
                ('time_end_working', models.TimeField()),
                ('capacity_gym', models.PositiveIntegerField()),
                ('state', models.IntegerField(choices=[(1, 'have capacity'), (2, 'full capacity')], default=1)),
                ('number_register_person', models.PositiveIntegerField(default=0)),
                ('monthly_tuition', models.PositiveIntegerField()),
                ('address_exact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('province', models.CharField(choices=[('1', 'Alborz'), ('2', 'Ardabil'), ('3', 'East Azerbaijan'), ('4', 'West Azerbaijan'), ('5', 'Bushehr'), ('6', 'Chahar Mahaal and Bakhtiari'), ('7', 'Fars'), ('8', 'Gilan'), ('9', 'Golestan'), ('10', 'Hamadan'), ('11', 'Hormozgan'), ('12', 'Ilam'), ('13', 'Isfahan'), ('14', 'Kerman'), ('15', 'Kermanshah'), ('16', 'North Khorasan'), ('17', 'Razavi Khorasan'), ('18', 'South Khorasan'), ('19', 'Khuzestan'), ('20', 'Kohgiluyeh and Boyer-Ahmad'), ('21', 'Kurdistan'), ('22', 'Lorestan'), ('23', 'Markazi'), ('24', 'Mazandaran'), ('25', 'Qazvin'), ('26', 'Qom'), ('27', 'Semnan'), ('28', 'Sistan and Baluchestan'), ('29', 'Tehran'), ('30', 'Yazd'), ('31', 'Zanjan')], max_length=2)),
                ('name_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRegisterInGym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.UUIDField(editable=False)),
                ('student_email', models.EmailField(max_length=254)),
                ('time_register', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[gyms.validations.get_words])),
                ('last_name', models.CharField(max_length=50, validators=[gyms.validations.get_words])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('image_person', models.ImageField(upload_to='image/')),
                ('national_code', models.CharField(max_length=10, validators=[gyms.validations.check_national_code, gyms.validations.check_exists_code_national])),
                ('number_phone', models.CharField(max_length=11, validators=[gyms.validations.true_phone_number])),
                ('favorite_sport', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Football'), (2, 'Volleyball'), (3, 'Swim'), (4, 'Basketball'), (5, 'Tennis'), (6, 'Table Tennis'), (7, 'Baseball'), (8, 'Golf'), (9, 'Wrestling'), (10, 'Bodybuilding'), (11, 'Boxing'), (12, 'Kung Fu'), (13, 'Karate'), (14, 'MMA'), (15, 'shooting'), (16, 'Jujitsu'), (17, 'taekwondo'), (18, 'water polo'), (19, 'Running'), (20, 'Mountaineering'), (21, 'Field hockey'), (22, 'bowling'), (23, 'handball'), (24, 'American football'), (25, 'futsal')], max_length=100)),
                ('credit', models.PositiveIntegerField(default=0, editable=False)),
                ('gyms', models.ManyToManyField(blank=True, to='gyms.gyms')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.locations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[gyms.validations.get_words])),
                ('last_name', models.CharField(max_length=50, validators=[gyms.validations.get_words])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('number_phone', models.CharField(max_length=11, validators=[gyms.validations.true_phone_number])),
                ('image_person', models.ImageField(upload_to='image/')),
                ('national_code', models.CharField(max_length=10, validators=[gyms.validations.check_national_code, gyms.validations.check_exists_code_national])),
                ('salary', models.PositiveIntegerField(default=0, editable=False)),
                ('profession', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Football'), (2, 'Volleyball'), (3, 'Swim'), (4, 'Basketball'), (5, 'Tennis'), (6, 'Table Tennis'), (7, 'Baseball'), (8, 'Golf'), (9, 'Wrestling'), (10, 'Bodybuilding'), (11, 'Boxing'), (12, 'Kung Fu'), (13, 'Karate'), (14, 'MMA'), (15, 'shooting'), (16, 'Jujitsu'), (17, 'taekwondo'), (18, 'water polo'), (19, 'Running'), (20, 'Mountaineering'), (21, 'Field hockey'), (22, 'bowling'), (23, 'handball'), (24, 'American football'), (25, 'futsal')], max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.locations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gyms',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.locations'),
        ),
        migrations.AddField(
            model_name='gyms',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.master'),
        ),
        migrations.AddField(
            model_name='gyms',
            name='time_register_student',
            field=models.ManyToManyField(blank=True, to='gyms.timeregisteringym'),
        ),
        migrations.CreateModel(
            name='BlockStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_student', models.EmailField(max_length=254)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gyms')),
            ],
        ),
    ]
