# Generated by Django 4.1.5 on 2023-02-09 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gyms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('fm', 'Female & Male')], max_length=2)),
                ('field_sport_gym', models.IntegerField(choices=[(1, 'Football'), (2, 'Volleyball'), (3, 'Swim'), (4, 'Basketball'), (5, 'Tennis'), (6, 'Table Tennis'), (7, 'Baseball'), (8, 'Golf'), (9, 'Wrestling'), (10, 'Bodybuilding'), (11, 'Boxing'), (12, 'Kung Fu'), (13, 'Karate'), (14, 'MMA'), (15, 'shooting'), (16, 'Jujitsu'), (17, 'taekwondo'), (18, 'water polo'), (19, 'Running'), (20, 'Mountaineering'), (21, 'Field hockey'), (22, 'bowling'), (23, 'handball'), (24, 'American football'), (25, 'futsal')])),
                ('days_work', models.CharField(choices=[('S', 'Saturday'), ('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('T', 'Thursday'), ('F', 'Friday')], max_length=100)),
                ('time_start_working', models.TimeField(unique=True)),
                ('time_end_working', models.TimeField(unique=True)),
                ('capacity_gym', models.PositiveIntegerField()),
                ('state', models.IntegerField(choices=[(1, 'have capacity'), (2, 'full capacity')], default=1)),
                ('number_register_person', models.PositiveIntegerField(default=0)),
                ('monthly_tuition', models.PositiveIntegerField()),
                ('address_exact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('province', models.CharField(choices=[('A', 'Alborz'), ('A', 'Ardabil'), ('E', 'East Azerbaijan'), ('W', 'West Azerbaijan'), ('B', 'Bushehr'), ('C', 'Chahar Mahaal and Bakhtiari'), ('F', 'Fars'), ('G', 'Gilan'), ('G', 'Golestan'), ('H', 'Hamadan'), ('H', 'Hormozgan'), ('I', 'Ilam'), ('I', 'Isfahan'), ('K', 'Kerman'), ('K', 'Kermanshah'), ('N', 'North Khorasan'), ('R', 'Razavi Khorasan'), ('S', 'South Khorasan'), ('K', 'Khuzestan'), ('K', 'Kohgiluyeh and Boyer-Ahmad'), ('K', 'Kurdistan'), ('L', 'Lorestan'), ('M', 'Markazi'), ('M', 'Mazandaran'), ('Q', 'Qazvin'), ('Q', 'Qom'), ('S', 'Semnan'), ('S', 'Sistan and Baluchestan'), ('T', 'Tehran'), ('Y', 'Yazd'), ('Z', 'Zanjan')], max_length=1)),
                ('name_city', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('image_person', models.ImageField(upload_to='image_student/')),
                ('national_code', models.CharField(max_length=11)),
                ('number_phone', models.CharField(max_length=11)),
                ('credit', models.PositiveIntegerField(default=0, editable=False)),
                ('gyms', models.ManyToManyField(blank=True, to='gyms.gyms')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.locations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('number_phone', models.CharField(max_length=11)),
                ('image_profiles', models.ImageField(upload_to='image_master/')),
                ('national_code', models.CharField(max_length=11)),
                ('credit', models.PositiveIntegerField(default=0, editable=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.locations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gyms',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.locations'),
        ),
        migrations.AddField(
            model_name='gyms',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.master'),
        ),
    ]
