# Generated by Django 4.1.5 on 2023-02-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='name_city',
            field=models.CharField(max_length=100),
        ),
    ]
