# Generated by Django 4.1.5 on 2023-02-20 17:49

from django.db import migrations, models
import gyms.validations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='first_name',
            field=models.CharField(max_length=50, validators=[gyms.validations.get_words]),
        ),
        migrations.AlterField(
            model_name='master',
            name='last_name',
            field=models.CharField(max_length=50, validators=[gyms.validations.get_words]),
        ),
        migrations.AlterField(
            model_name='master',
            name='national_code',
            field=models.CharField(max_length=10, validators=[gyms.validations.check_national_code]),
        ),
        migrations.AlterField(
            model_name='master',
            name='number_phone',
            field=models.CharField(max_length=11, validators=[gyms.validations.true_phone_number]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, validators=[gyms.validations.get_words]),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, validators=[gyms.validations.get_words]),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_code',
            field=models.CharField(max_length=10, validators=[gyms.validations.check_national_code]),
        ),
        migrations.AlterField(
            model_name='student',
            name='number_phone',
            field=models.CharField(max_length=11, validators=[gyms.validations.true_phone_number]),
        ),
    ]
