# Generated by Django 4.1.5 on 2023-02-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='credit',
            new_name='salary',
        ),
    ]
