# Generated by Django 4.1.5 on 2023-07-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_student_new_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='new_notification',
            field=models.TextField(default='0'),
        ),
    ]
