# Generated by Django 4.1.5 on 2023-02-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_alter_student_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='credit',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
