# Generated by Django 4.1.5 on 2023-03-14 07:38

from django.db import migrations, models
import gyms.validations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_student_favorite_sport_alter_gyms_days_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyms',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[gyms.validations.get_words]),
        ),
        migrations.AlterField(
            model_name='gyms',
            name='time_end_working',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='gyms',
            name='time_start_working',
            field=models.TimeField(),
        ),
    ]
