# Generated by Django 4.1.5 on 2023-03-16 12:29

from django.db import migrations, models
import gyms.validations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_alter_gyms_name_alter_gyms_time_end_working_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyms',
            name='name',
            field=models.CharField(max_length=50, validators=[gyms.validations.get_words]),
        ),
    ]
