# Generated by Django 4.1.5 on 2023-03-22 17:22

from django.db import migrations, models
import gyms.validations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_alter_gyms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='national_code',
            field=models.CharField(max_length=10, validators=[gyms.validations.check_national_code, gyms.validations.check_exists_code_national]),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_code',
            field=models.CharField(max_length=10, validators=[gyms.validations.check_national_code, gyms.validations.check_exists_code_national]),
        ),
    ]
