# Generated by Django 4.1.5 on 2023-03-26 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_alter_master_national_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRegisterInGym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_register', models.DateTimeField(auto_now=True)),
                ('student', models.ManyToManyField(to='gyms.student')),
            ],
        ),
        migrations.AddField(
            model_name='gyms',
            name='time_registered_student',
            field=models.ManyToManyField(blank=True, to='gyms.timeregisteringym'),
        ),
    ]
