# Generated by Django 4.1.5 on 2023-03-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_remove_gyms_time_registered_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='time_registered_gym',
        ),
        migrations.AddField(
            model_name='gyms',
            name='time_register_student',
            field=models.ManyToManyField(blank=True, to='gyms.timeregisteringym'),
        ),
        migrations.AddField(
            model_name='timeregisteringym',
            name='student_email',
            field=models.EmailField(default='aliascandari@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
