# Generated by Django 4.1.5 on 2023-04-05 11:12

from django.db import migrations, models
import gyms.validations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_remove_student_time_registered_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyms',
            name='name',
            field=models.CharField(max_length=30, validators=[gyms.validations.get_words]),
        ),
    ]
