# Generated by Django 4.1.5 on 2023-04-05 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_alter_gyms_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_student', models.EmailField(max_length=254)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gyms')),
            ],
        ),
    ]
