# Generated by Django 4.1.5 on 2023-05-19 21:49

from django.db import migrations, models
import django.db.models.deletion
import gyms.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250, validators=[gyms.validations.get_words])),
                ('name_gym', models.CharField(max_length=150, validators=[gyms.validations.get_words])),
                ('question', models.TextField()),
                ('time_question', models.DateTimeField(auto_now=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.student')),
            ],
            options={
                'index_together': {('topic', 'student_user', 'time_question')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('topic', models.CharField(max_length=150, validators=[gyms.validations.get_words])),
                ('time_notification', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gyms')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.master')),
            ],
            options={
                'index_together': {('gym', 'topic', 'time_notification')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250, validators=[gyms.validations.get_words])),
                ('name_gym', models.CharField(max_length=150, validators=[gyms.validations.get_words])),
                ('answer', models.TextField()),
                ('time_answer', models.DateTimeField(auto_now=True)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.master')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.question')),
            ],
            options={
                'index_together': {('topic', 'master_user', 'time_answer')},
            },
        ),
    ]
