# Generated by Django 4.1.5 on 2023-07-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='question',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='question',
            name='student_user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
